trigger:
- azure-pipelines

extends:
  template: build-pipeline.yml
  parameters:
    optionalStep: false
    description: 'blah'
    extraSteps:
      - task: Npm@1
        displayName: 'Test the scss foundation library'
        inputs:
          command: 'custom'
          customCommand: 'run test'
          workingDir: 'projects/scss-foundation'
