parameters:
- name: optionalStep
  type: boolean
  default: true
- name: extraSteps
  type: stepList
  default: []
- name: description
  type: string
  default: ''

stages:
- stage: Preparation
  pool:
    vmImage: ubuntu-latest

  jobs:
  - job: NPM
    steps:
    - task: Npm@1
      displayName: 'npm install scss foundation $(MajorMinorVersion)'
      inputs:
        command: 'install'
        workingDir: 'projects/scss-foundation'    

    - ${{ if eq(parameters.optionalStep, true) }}:
      - task: Npm@1
        displayName: 'Lint the scss foundation library ${{ parameters.description }}'
        inputs:
          command: 'custom'
          customCommand: 'run lint'
          workingDir: 'projects/scss-foundation'
        
    - ${{ each step in parameters.extraSteps }}:
      - ${{ each pair in step }}:
          ${{ if ne(pair.value, 'CmdLine@2') }}:
            ${{ pair.key }}: ${{ pair.value }}       
          ${{ if eq(pair.value, 'CmdLine@2') }}: 
            # Step is rejected by raising a YAML syntax error
            '${{ pair.value }}': error 

    - script: echo This happens after code
      displayName: 'Done'