trigger:
- master

# no PR triggers
pr: none

pool:
  vmImage: windows-latest

steps:
- task: Npm@1
  displayName: 'npm ci'
  inputs:
    command: 'ci'
- task: Npm@1
  displayName: 'Build docs application'
  inputs:
    command: 'custom'
    customCommand: 'run build @enigmatry/demo-app'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/dist/enigmatry/apps/demo-app'
    output_location: '/'
    azure_static_web_apps_api_token: $(deployment_token)
  displayName: 'Deploy docs application'
