trigger:
- master

# no PR triggers
pr: none

pool:
  vmImage: ubuntu-latest

  # This determines the build number
name: $(MajorMinorVersion)$(Rev:.r)

steps:    
- task: Npm@1
  displayName: 'Set the version stylelint recommended rules'
  inputs:
    command: custom
    customCommand: version $(Build.Buildnumber) --no-git-tag-version
    workingDir: 'libs/stylelint-config'

- task: Npm@1
  displayName: 'Publish the stylelint recommended rules'
  inputs:
    command: publish
    publishRegistry: useExternalRegistry
    publishEndpoint: npm
    workingDir: 'libs/stylelint-config'